name: Frontend and Infrastructure CI-CD

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # workflow_dispatch:

jobs:
  build-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      # Install Terraform CLI
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      # Check formatting
      - name: Terraform format
        run: terraform fmt -check -recursive

      # Initialize Terraform
      - name: Terraform init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
